[workspace]
resolver = "3"
members = [
    "reverie"
]

[profile.release]
opt-level = "s"
strip = true

[workspace.dependencies]
actson = "2.1.0"
async-stream = "0.3.6"
async-trait = "0.1.89"
dashmap = "6.2.1"
eventsource-stream = "0.2.3"
fjall = "3.1.4"
futures-core = "0.3.32"
futures-util = { version = "0.3.32", default-features = false, features = ["std"] }
http-body-util = "0.1.3"
hyper = { version = "1.10.1", default-features = false }
hyper-rustls = { version = "0.27.3", default-features = false, features = ["native-tokio", "http1", "http2", "ring", "tls12"] }
hyper-util = { version = "0.1.20", default-features = false, features = ["client", "http1", "http2", "tokio", "client-legacy"] }
nu-ansi-term = "0.50.3"
rootcause = "0.12.1"
rootcause-tracing = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["preserve_order"] }
thiserror = "2.0.18"
time = { version = "0.3.47", default-features = false, features = ["formatting", "serde"] }
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread", "fs", "net", "signal", "sync", "process"] }
toml = { version = "1.1.2", default-features = false, features = ["parse", "serde", "std"] }
tower = { version = "0.5.3", features = ["filter", "timeout", "tracing", "util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
twilight-gateway = { version = "0.17.1", default-features = false, features = ["rustls-native-roots"] }
twilight-http = { version = "0.17.1", default-features = false, features = ["rustls-native-roots"] }
twilight-model = "0.17.1"
uuid = { version = "1.23.2", features = ["serde", "v7"] }
