[package]
name = "reverie"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
fjall.workspace = true
futures-core.workspace = true
futures-util.workspace = true
nu-ansi-term.workspace = true
reverie-adapter.workspace = true
reverie-core.workspace = true
reverie-discord = { workspace = true, optional = true }
reverie-openai.workspace = true
reverie-util.workspace = true
rootcause.workspace = true
rootcause-tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[features]
default = ["discord"]
discord = ["dep:reverie-discord"]
