use std::io;

use futures_core::Stream;
use futures_core::stream::BoxStream;
use futures_util::StreamExt;
use tracing::Span;
use uuid::Uuid;

/// Represents elements that make up an LLM's streaming response.
///
/// The stream is represented using a flattened stream consisting of many 'inner' streams
/// (or "channels").
#[derive(Debug, Clone)]
pub enum ResponseEvent {
    /// Optional reasoning done by the LLM.
    ///
    /// Reasoning can arrive in chunks.
    Reasoning(String),
    /// The LLM is outputing a text response message.
    Message(MessageEvent),
    /// The LLM is calling a tool.
    Tool(ToolEvent),
    /// A tool call is being executed and the result is being streamed.
    ToolResult(ToolResultEvent),
}

/// All events related to response messages created by the LLM.
#[derive(Debug, Clone)]
pub enum MessageEvent {
    /// Sent when the LLM has started generating a new message response.
    Start { index: ChannelIndex },
    /// A chunk of text to append to a specific response.
    Chunk { index: ChannelIndex, delta: String },
    /// Indicates a certain response is complete.
    Complete { index: ChannelIndex },
}

/// All events related to tool calls performed by the LLM.
#[derive(Debug, Clone)]
pub enum ToolEvent {
    /// Sent when the LLM starts calling a tool.
    Start {
        index: ChannelIndex,
        tool_call_id: String,
        name: String,
        /// If true, this tool call is being handled already (by middleware for example). Tool
        /// output will follow in the same stream.
        handled: bool,
    },
    /// A chunk to append to a specific tool call's arguments.
    Chunk { index: ChannelIndex, delta: String },
    /// Indicates the LLM has finished generating the tool arguments.
    Complete { index: ChannelIndex },
}

/// All events related to a tool's output.
#[derive(Debug, Clone)]
pub enum ToolResultEvent {
    /// Sent when the tool output starts being streamed.
    Start {
        index: ChannelIndex,
        tool_call_id: String,
        name: String,
    },
    /// Sent for each chunk of the tool output.
    Chunk { index: ChannelIndex, delta: String },
    /// Sent when the tool output is complete.
    Complete { index: ChannelIndex },
}

/// Unique identifier for a channel (reasoning, response, tool, ...) in a stream.
///
/// Initially simple ascending usize indices were used here, but this gets unwieldy fast when
/// middleware are intercepting and creating new channels. UUIDv7 is significantly more convenient
/// at a neglibile cost, still sorts based on time, and could prevent some oversights.
pub type ChannelIndex = Uuid;

/// A streaming response generated by an LLM.
pub struct ResponseStream {
    inner: BoxStream<'static, io::Result<ResponseEvent>>,
    span: Span,
}

impl Unpin for ResponseStream {}

impl ResponseStream {
    /// Wraps an existing stream.
    pub fn new<S>(stream: S) -> Self
    where
        S: Stream<Item = io::Result<ResponseEvent>> + Send + 'static,
    {
        Self {
            inner: stream.boxed(),
            span: Span::none(),
        }
    }

    /// Returns the stream with the current span attached.
    pub fn instrumented(mut self) -> Self {
        self.span = Span::current();
        self
    }
}

impl Stream for ResponseStream {
    type Item = io::Result<ResponseEvent>;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let this = self.get_mut();

        let _guard = this.span.enter();

        this.inner.poll_next_unpin(cx)
    }
}
